# Site settings
title: Student Union
email: you@example.com
description: > # this means to ignore newlines until "baseurl:"
 Student Union
baseurl:  # the subpath of your site, e.g. /blog/
page.path: {{ page.path }}

url:  studentunion.co # the base hostname & protocol for your site
twitter_username: twitter_username
github_username:  github_username


# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  poetry:
    output: true
    permalink: /poetry/:path/


