# Site settings
title: Student Union
email: studentunion@rbs.lv
description: > # this means to ignore newlines until "baseurl:"
 The Riga Business School Student Union stands for the interests of all RBS students. We build a community of leaders who leave a positive impact on society.



url:  studentunion.co # the base hostname & protocol for your site
twitter_username: twitter_username
github_username:  github_username


# Build settings
markdown: kramdown

highlighter: rouge
baseurl:  # the subpath of your site, e.g. /blog/
# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  poetry:
    output: true
    permalink: /poetry/:path/


