# Site settings
title: Student Union
email: studentunion@rbs.lv
description: > # this means to ignore newlines until "baseurl:"
 Student Union



url:  studentunion.co # the base hostname & protocol for your site
twitter_username: twitter_username
github_username:  github_username


# Site settings
title: CURLS BEFORE GIRLS
description: "Your go-to place for Bodybuilding and Fitness related content!"
url: "https://peerkons.github.io/curlsbeforegirls/"
author:
  name: "Pauls Perkons"
  email: "thunderpuls@gmail.com"
  url: "https://peerkons.github.io/curlsbeforegirls/"

# Build settings
markdown: kramdown

highlighter: rouge
baseurl:  # the subpath of your site, e.g. /blog/
# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  poetry:
    output: true
    permalink: /poetry/:path/


